human/urls.py
from django.urls import path

from .views import(
    employeesList,
    employeeCreate,
    employeeUpdate,
    employeeDelete,
    employeeView,

    loginPage,
    logoutUser
)

app_name='human'

urlpatterns = [
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),


    path('', employeesList, name='list'),
    path('create/', employeeCreate, name='create'),
    path('update/<str:pk>/', employeeUpdate, name='update'),
    path('delete/<str:pk>/', employeeDelete, name='delete'),
    path('<str:pk>/', employeeView, name='view'),



]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('product/', include('product.urls')),
    path('human/', include('human.urls')),

    path('orders/', include('orders.urls')),
    path('reports/', include('reports.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

human/models.py
from django.db import models
from django.contrib.auth.models import User


class Department(models.TextChoices):
    PROD = 'P', 'Produção'
    HUMANOS = 'RH', 'Recursos Humanos'
    QUALIDADE = 'Q', 'Qualidade'
    LOGISTICA = 'L', 'Logistica'
    MANUTENCAO = 'M', 'Manutenção'


class Employee(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    department = models.CharField(
        max_length=3,
        choices=Department.choices,
        default=Department.PROD
    )
    image = models.ImageField(upload_to='func' ,default='random.jpg')
    contact = models.CharField(max_length=150, blank=True, null=True)
    nationality = models.CharField(max_length=150, default='portuguesa')
    address = models.CharField(max_length=150, blank=True, null=True)
    

    def name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Client(models.Model):
    name = models.CharField(max_length=120)
    logo = models.ImageField(upload_to='clients/', default='random.jpg')

    def __str__(self):
        return str(self.name)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    avatar = models.ImageField(upload_to='users/', null=True, default='transferir.jpg')


    def __str__(self):
        return self.user.username

human/forms.py
from django import forms
from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

human/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

import pandas as pd

from .models import Employee, Profile
from .forms import EmployeeForm
from product.models import Production, ProductionOrder
from .utils import get_employee_by_id, get_prod_order_by_id


# Gerir Users
def loginPage(request):
    """Verificar se o user já se encontra logado, se for o caso não pode aceder a esta pagina novamente"""
    if request.user.is_authenticated:
        return redirect('dashboard:home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User Not Found!', 'alert-warning alert-dismissible')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('dashboard:home')
        else:
            messages.error(request, 'As credênciais estão erradas!', 'alert-warning alert-dismissible')

    context = {}

    return render(request, 'human/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('human:login')





# Gerir funcionários
def employeesList(request):
    employees = Employee.objects.filter()
    form = EmployeeForm()
    if request.method == 'POST':
        form = EmployeeForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            messages.success(request, 'Funcionário adicionado com sucesso!', 'alert-success alert-dismissible')
        else:
            messages.error(request, 'Erro ao Validar o Formulário!', 'alert-warning alert-dismissible')

    context= {
        'objects':employees,
        'form': form,
    }
    return render(request, 'human/list.html', context)

def employeeCreate(request):
    form = EmployeeForm()
    if request.method == 'POST':
        form = EmployeeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Funcionário adicionado com sucesso!', 'alert-success alert-dismissible')
            return redirect('human:list')
    
    context = {'form':form}
    return render(request, 'human/create.html', context)

def employeeUpdate(request, pk):
    employee = get_object_or_404(Employee, id=pk)
    form = EmployeeForm(instance=employee)
    if request.method == 'POST':
        form = EmployeeForm(request.POST, request.FILES, instance=employee)
        if form.is_valid():
            form.save()
            messages.success(request, 'Funcionário modificado com sucesso!', 'alert-success alert-dismissible')
            return redirect('human:view', pk=employee.id)

    context = {
        'employee':employee,
        'form':form,
    }
    return render(request, 'human/update.html', context)

def employeeDelete(request, pk):
    employee = get_object_or_404(Employee, id=pk)
    if request.method == 'POST':
        employee.delete()
        messages.success(request, 'Funcionário adicionado com sucesso!', 'alert-success alert-dismissible')
        return redirect('human:list')
    
    context = {
        'obj':employee,
    }

    return render(request, 'delete.html', context)

def employeeView(request, pk):
    productions_df = None
    prod_product_df = None
    result = None

    employee = Employee.objects.get(id=pk)
    productions = Production.objects.filter(employee=employee)

    productions_df = pd.DataFrame(productions.values())
    productions_df['employee_id'] = productions_df['employee_id'].apply(get_employee_by_id)
    productions_df['production_order_id'] = productions_df['production_order_id'].apply(get_prod_order_by_id)
    productions_df['date'] = productions_df['date'].apply(lambda x: x.strftime('%Y-%m-%d'))
    productions_df.rename({'id':'Prod', 'production_order_id':'Ordem Prod', 'employee_id':'Funcionario', 'quantity':'Quantidade', 'time':'Tempo de Prod', 'date': 'data'}, axis=1, inplace=True)

    prod_product_data = []
    for production in productions:
        prod_product = {
            'Ordem Prod': production.production_order.prod_order_id,
            'Produto': production.production_order.product,
        }
        prod_product_data.append(prod_product)

    prod_product_df = pd.DataFrame(prod_product_data)
    result = pd.merge(productions_df, prod_product_df, on='Ordem Prod')
        


    print(productions_df)
    print('*********')
    print(prod_product_df)
    print('*********')
    print(result)

    productions_df = productions_df.to_html()
    result = result.to_html()

    context = {
        'obj':employee,
        'productions':productions,
        'productions_df':productions_df,
        'result':result,
    }
    return render(request, 'human/view.html', context)

human/templates/human/list.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}




<!-- Modal -->
<div class="modal fade" id="employeeModal" tabindex="-1" aria-labelledby="employeeModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="employeeModal">Adicionar Funcionário</h5>
                <button type="button" class="btn btn-warning" data-bs-dismiss="modal" aria-label="Close"><i
                        class="fa-solid fa-xmark"></i></button>
            </div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body">
                    <!-- first_name , last_name -->
                    {{ form.first_name.errors }}
                    {{ form.last_name.errors }}
                    <div class="input-group mb-3">
                        <span class="input-group-text">Primeiro e Ultimo Nome</span>
                        <input type="text" aria-label="First name" class="form-control" name="first_name">
                        <input type="text" aria-label="Last name" class="form-control" name="last_name">
                    </div>
                    {{ form.email.errors }}

                    <!-- Email -->
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Email</span>
                        <input type="email" class="form-control" placeholder="Email" aria-label="Email" name="email"
                            aria-describedby="basic-addon1">
                    </div>
                    <!-- department -->
                    {{ form.department.errors }}
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="inputGroupSelect01">Departamento</label>
                        <select class="form-select" id="inputGroupSelect01" name="department">
                            <option selected disabled>Choose...</option>
                            {% for choice in form.department.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    {{ form.image.errors }}
                    <!-- Escolher Imagem  -->
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="inputGroupFile01">Fotografia</label>
                        <input type="file" class="form-control" id="inputGroupFile01" name="image">
                    </div>
                    {{ form.contact.errors }}
                    <!-- Contacto -->
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Tel.</span>
                        <input type="text" class="form-control" placeholder="Contact" aria-label="Contact"
                            aria-describedby="basic-addon1" name="contact">
                    </div>
                    {{ form.nationality.errors }}
                    <!-- Nacionalidade -->
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Nacionalidade</span>
                        <input type="text" class="form-control" placeholder="Nationality" aria-label="Nationality"
                            aria-describedby="basic-addon1" name="nationality">
                    </div>
                    {{ form.addres.errors }}
                    <!-- Morada -->
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Morada</span>
                        <input type="text" class="form-control" placeholder="Address" aria-label="Address"
                            aria-describedby="basic-addon1" name="address">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-warning border-2 text-bottom p-2">Confirmar<span
                            class="badge bg-dark mx-2"><i class="fa-solid fa-check"></i></span></button>
                </div>
            </form>
        </div>
    </div>
</div>




<main class="content px-3 py-2">
    <div class="container-fluid">
        <div class="mb-3 text-center">
            <h4> Tabela de Funcionários</h4>
        </div>
        <div class="action mb-4 text-end">
            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#employeeModal"><i
                    class="fa-solid fa-plus"></i></button>
        </div>


        <div class="card border-0">
            <!-- Start Table Produtos -->
            <div class="card-body text-center">
                <table class="table bg-white">
                    <thead class="thead-dark">
                        <tr class="table-dark">
                            <th scope="col">#</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Email</th>
                            <th scope="col">Departamento</th>
                            <th scope="col">Atividade</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in objects %}
                        <tr>
                            <th scope="row">{{obj.id}}</th>
                            <td>{{obj.first_name}} {{obj.last_name}}</td>
                            <td>{{obj.email}}</td>
                            <td>{{obj.department}}</td>
                            <td class="text-center">
                                <a class='btn btn-warning btn-sm' href="{% url 'human:view' obj.id %}"><i
                                        class="fa-regular fa-eye"></i></a>
                                <!-- Button triger modal -->
                                <a id="edit-btn" type='button' class='btn btn-success btn-sm edit-btn'
                                    href="{% url 'human:update' obj.id %}"><i class="fa-solid fa-pen-to-square"></i></a>
                                <a class='btn btn-danger btn-sm' href="{% url 'human:delete' obj.id %}"><i
                                        class="fa-regular fa-circle-xmark"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

human/templates/human/login.html
{% extends 'main.html' %}

{% block content %}
<main class="content px-3 py-2">
    <div class="form-login">
        <form method="POST" action="">
            {% csrf_token %}
            <div class="wrapper-login">
                <h1>Login</h1>
                <div class="input-box">
                    <input type="text" name="username" placeholder="Username" required>
                    <i class='bx bxs-user'></i>
                </div>
                <div class="input-box">
                    <input type="password" name="password"
                        placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;" required>
                    <i class='bx bxs-lock-alt'></i>
                </div>
                <div class="remember-forgot">
                    <label><input type="checkbox">Remember me</label>
                    <a href="#">Forgot password?</a>
                </div>
                <button type="submit" class="btn btn-warning">Login</button>

                <div class="register-link">
                    <p>Don't have an account?
                        <a href="#">Register</a>
                    <p>
                </div>
            </div>
            </body>
        </form>
    </div>
</main>

{% endblock content %}

human/templates/human/update.html
{% extends 'main.html' %}
{% block content %}

<div class="form__product">
    <div class="content px-3 py-2">
        {% include 'form.html' %}

    </div>
</div>

{% endblock content %}

human/templates/human/view.html
{% extends 'main.html' %}
{% block content %}
<main class="content px-3 py-2">
    <div class="container-fluid">
        {{data_df|safe}}

        <div class="mb-4 text-center">
            <h4>Informações {{obj.name}}</h4>
        </div>
        <div class="d-flex justify-content-end mb-4">
            <a href="{% url 'human:update' obj.id %}"> <button type="button" class="btn btn-outline-warning ">
                    <i class="fa-solid fa-pen-to-square"></i></button>
            </a>
        </div>
        <!-- Informação Funcionário -->
        <div class="row">
            <div class="col d-flex">
                <div class="card flex-fill border-0 illustration">
                    <div class="card-body p-0 d-flex flex-fill">
                        <div class="row g-0 w-100">
                            <div class="col-8">
                                <div class="p-3 m-1">
                                    <ul class="list-group">
                                        <li class="list-group-item list-group-item-warning text-center">
                                            <strong>{{obj.name}}</strong>
                                        </li>
                                        <li class="list-group-item list-group-item-secondary"> Departamento:
                                            <strong>{{obj.get_department_display}}</strong>
                                        </li>
                                        <li class="list-group-item list-group-item-secondary"> Email:
                                            <strong>{{obj.email}}</strong>
                                        </li>
                                        <li class="list-group-item list-group-item-secondary"> Tel. :<strong>+351
                                                {{obj.contact}}</strong></li>
                                        <li class="list-group-item list-group-item-secondary"> Morada:
                                            <strong>{{obj.address}}</strong>
                                        </li>
                                        <li class="list-group-item list-group-item-secondary"> Nacionalidade:
                                            <strong>{{obj.nationality}}</strong>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-4 align-self-end text-end">
                                <img src="{{obj.image.url}}" class="img-fluid illustration-img" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Fim Informações gerais Funcionário-->
            </div>
        </div>

        <!-- Calculos de Produtividade -->

        <!-- Fim Calculos de Produtividade -->


        <!-- Ínicio Informações de Produção -->
        <div class="row my-4">
            <div class="col d-flex">
                <div class="card flex-fill border-0 illustration p-2 my-2">
                    <div class="card-body p-0 d-flex flex-fill">
                        <div class="row g-0 w-100">
                            <!-- Lista Produções -->
                            <div class="col-8 d-flex">
                                <div class="p-3 m-1">
                                    <ul class="list-group">
                                        <li
                                            class="list-group-item list-group-item-warning d-flex justify-content-between">
                                            <strong>Produções Do Produto {{obj.name}}</strong>
                                        </li>
                                        {% for item in productions %}
                                        <li class="list-group-item list-group-item-secondary">
                                            <strong>{{item.employee}} - {{item.quantity}}
                                                ({{item.date.day}}/{{item.date.month}}/{{item.date.year}})</strong>
                                            <span
                                                class="badge bg-secondary rounded-pill align-self-end">{{item.quantity}}</span>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>




{% endblock content %}