human/urls.py
from django.urls import path

from .views import(
    employeesList,
    employeeCreate,
    employeeUpdate,
    employeeDelete,
    employeeView,

    loginPage,
    logoutUser
)

app_name='human'

urlpatterns = [
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),


    path('', employeesList, name='list'),
    path('create/', employeeCreate, name='create'),
    path('update/<str:pk>/', employeeUpdate, name='update'),
    path('delete/<str:pk>/', employeeDelete, name='delete'),
    path('<str:pk>/', employeeView, name='view'),



]

reports/urls.py
from django.urls import path

from .views import (
    ReportListView,
    ReportDetailView,
    UploadTemplateView,
    csv_upload,
    createReport,
    updateReport,
    renderPDF,
)

app_name = 'reports'

urlpatterns = [
    path('list/', ReportListView.as_view(), name='list'),
    path('upload/', csv_upload, name='upload'),
    path('from-file/', UploadTemplateView.as_view(), name='from-file'),
    path('create-report/', createReport, name='create-report'),
    path('update-report/<str:pk>/', updateReport, name='update-report'),

    path('detail/<str:pk>/', ReportDetailView.as_view(), name='detail'),
    path('detail/<str:pk>/pdf/', renderPDF, name='pdf'),

]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('product/', include('product.urls')),
    path('human/', include('human.urls')),

    path('orders/', include('orders.urls')),
    path('reports/', include('reports.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

reports/models.py
from django.db import models
from django.urls import reverse

#my apps imports
from human.models import Profile



class Report(models.Model):
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to='reports', blank=True)
    text = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return f'{self.name} ({self.created})'

    class Meta:
        ordering = ['-created']

reports/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['name', 'text']

reports/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView
from django.http import HttpResponse, JsonResponse
import os
from django.conf import settings
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
import csv
from django.utils.dateparse import parse_date




# my app imports
from .models import Report
from .forms import ReportForm
from orders.models import Order, Position, CSV
from product.models import Product
from human.models import Client, Profile
from .utils import get_image

class ReportListView(ListView):
    model = Report
    template_name = 'reports/list.html'

class ReportDetailView(DetailView):
    model = Report
    template_name = 'reports/detail.html'

class UploadTemplateView(TemplateView):
    template_name = 'reports/from_file.html'

def csv_upload(request):
    if request.method == 'POST':
        csv_file_name = request.FILES.get('file').name
        csv_file = request.FILES.get('file')
        obj, created = CSV.objects.get_or_create(file_name=csv_file_name)

        if created:
            obj.csv_file = csv_file
            obj.save()
            with open(obj.csv_file.path, 'r') as f:
                reader = csv.reader(f)
                reader.__next__() # skip first row
                for row in reader:
                    transaction_id = row[1]
                    product = row[2]
                    quantity = row[3]
                    client = row[4]
                    date = parse_date(row[5])
                    
                    try:
                        product_obj = Product.objects.get(name=product)
                    except Product.DoesNotExist:
                        product_obj = None

                    if product_obj is not None:
                        client_obj, _ = Client.objects.get_or_create(name=client)
                        salesman_obj = Profile.objects.get(user=request.user)

                        position_obj = Position.objects.create(
                            product=product_obj,
                            quantity=quantity,
                            created=date,
                        )
                        order_obj, _ = Order.objects.get_or_create(
                            transaction_id=transaction_id,
                            client=client_obj,
                            salesman=salesman_obj,
                            created=date,
                        )
                        order_obj.positions.add(position_obj)
                        order_obj.save()
                return JsonResponse({'ex':False})
        else:
            return JsonResponse({'ex':True})
    
    return HttpResponse()

def createReport(request):
    if request.is_ajax():
            image = request.POST.get('image')
            img = get_image(image)

            profile = request.user.profile

            Report.objects.create(
                name=request.POST.get('name'),
                text=request.POST.get('text'),
                image = img,
                author=profile,
            )
            return JsonResponse({'msg':'send'})
    return JsonResponse({})

def updateReport(request, pk):
    report = Report.objects.get(id=pk)
    form = ReportForm(instance=report)
    if request.method == 'POST':
        form = ReportForm(request.POST, instance=report)
        if form.is_valid():
            form.save()
            return redirect('reports:list')
            

    context = {
        'report':report,
        'form':form,
    }
    return render(request, 'reports/update.html', context)


def renderPDF(request, pk):
    template_path = 'reports/pdf.html'
    obj = get_object_or_404(Report, pk=pk)
    context = {'obj':obj}

    response = HttpResponse(content_type='application/pdf')

    response['Content-Disposition'] = 'filename="report.pdf"'

    template=get_template(template_path)
    html = template.render(context)

    #create a pdf with pisa
    pisa_status = pisa.CreatePDF(
        html, dest=response
    )
    if pisa_status.err:
        return HttpResponse('Algo deu errado <pre>' + html + '</pre>')
    return response

reports/templates/reports/detail.html
{% extends 'main.html' %}
{% block content %}

<main class="content">
    <div class="container-fluid">
        <div class="card border-2 align-self-center">
            <div class="card-body">
                <div class="p-3 m-1">
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-warning d-flex justify-content-between">
                            <strong>{{object.name}}</strong>
                        </li>
                        {% if object.image %}
                        <li
                            class="list-group-item list-group-item-secondary d-flex justify-content-between text-center">
                            <img src="{{object.image.url}}" class="img-fluid" alt="{{object.name}}">
                        </li>
                        {% endif %}
                        <li class="list-group-item list-group-item-secondary d-flex justify-content-between">
                            <p>{{object.text}}</p>
                        </li>
                        <li class="list-group-item list-group-item-secondary d-flex justify-content-between">
                            <p>Autor: <b>{{object.author}}</b></p>
                        </li>
                        <li class="list-group-item list-group-item-secondary d-flex justify-content-between">
                            <p>Criado: <b>{{object.created|timesince}} ago</b></p>
                        </li>
                    </ul>
                    <div class="card-action text-center mt-4">
                        <a href="{% url 'reports:update-report' object.id %}" class="btn btn-warning btn-md"><i
                                class="fa-solid fa-pen-to-square"></i></a>
                        <a class="btn btn-danger" href="{% url 'reports:pdf' object.id %}">PDF</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>


{% endblock content %}

reports/templates/reports/from_file.html
{% extends 'main.html' %}
{% load static %}

{% block scripts %}
<script src="{% static 'reports/upload.js' %}" defer></script>
<script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
{% endblock scripts %}
{% block content %}
<div class="container">
    <div id="alert-box"></div>
    <div class="card">
        <h4 class="card-header bg-dark text-warning text-center">
            Upload CSV
        </h4>
        <div class="card-body">
            <form enctype="multipart/form-data" action="upload/" method="POST" class="dropzone dz" id="my-dropzone">
                {% csrf_token %}
                <div class="fallback">
                    <input name="file" type="file" multiple>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

reports/templates/reports/list.html
{% extends 'main.html' %}
{% block content %}

<main class="content px-3 py-2">
    <div class="container-fluid">
        <div class="mb-3">
            <h4> Relatórios </h4>
        </div>
        {% for obj in object_list %}
        <div class="list-group p-3 my-2">
            <a href="{{obj.get_absolute_url}}"
                class="list-group-item list-group-item-secondary flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="m-1">{{obj.name}}</h5>
                    <small>{{obj.created|timesince}} ago</small>
                </div>
                <hr>
                <p class="mb-1">{{obj.text}}
                </p>
                <p class="text-end">{{obj.author}}</p>
            </a>
        </div>
        <!-- <a href="{% url 'reports:update-report' obj.id %}" class="btn btn-warning btn-sm">Editar</a> -->
        {% endfor %}
    </div>
</main>


{% endblock content %}

reports/templates/reports/pdf.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" <title> PDF {{obj.name}} RELATÓRIO</title>
    <style>
        .image {
            width: 100%;
            height: auto;
        }
    </style>
</head>

<body>
    <h1>{{obj.name}}</h1>
    <hr>
    <img src="{{obj.image.path}}" class="image">
    <br>
    <h3>Observações:</h3>
    <p>{{obj.text}}</p>
    <hr>
    <p>Autor do relatório <b>{{obj.author}}</b></p>
    <p>Criado em <b>{{obj.created}}</b></p>
</body>

</html>

reports/templates/reports/update.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="form__product">
    <div class="content px-3 py-2">
        {% include 'form.html' %}
    </div>
</div>

{% endblock content %}