human/urls.py
from django.urls import path

from .views import(
    employeesList,
    employeeCreate,
    employeeUpdate,
    employeeDelete,
    employeeView,

    loginPage,
    logoutUser
)

app_name='human'

urlpatterns = [
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),


    path('', employeesList, name='list'),
    path('create/', employeeCreate, name='create'),
    path('update/<str:pk>/', employeeUpdate, name='update'),
    path('delete/<str:pk>/', employeeDelete, name='delete'),
    path('<str:pk>/', employeeView, name='view'),



]

product/urls.py
from django.urls import path

from .views import (
    productList,
    productCreate,
    productUpdate,
    productDelete,
    productView,

    inventaryView,

    productionView,
    addProduction,
    productionEdit,
    productionDelete,

    productionOrderView,
    createProductionOrder,
)

app_name = 'product'


urlpatterns = [
    #Product
    path('', productList, name='list'),
    path('create/', productCreate, name='create'),
    path('update/<str:pk>/', productUpdate, name='update'),
    path('delete/<str:pk>/', productDelete, name='delete'),
    path('product/<str:pk>/', productView, name='view'),

    #Inventary
    path('inventary/', inventaryView, name="inv"),

    #Productions
    path('production/', productionView, name='prod'),
    path('add-prod/', addProduction, name='add-prod'),
    path('prod-edit/<str:pk>/', productionEdit, name='prod-edit'),
    path('prod-del/<str:pk>/', productionDelete, name='prod-del'),

    #Ordem Produção
    path('productionOrderView/', productionOrderView, name='production-order'),
    path('createProductionOrder/', createProductionOrder, name='add-prod-order'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('product/', include('product.urls')),
    path('human/', include('human.urls')),

    path('orders/', include('orders.urls')),
    path('reports/', include('reports.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

product/models.py
from django.db import models
from django.utils import timezone
import uuid
from human.models import Employee


class Product(models.Model):

    CATEGORY = {
    "SHIELD" : "SHIELD",
    "BRACKET" : "BRACKET",
    "ASSEMBLY" : "HANGER ASSEMBLY",
    }
    name=models.CharField(max_length=120, verbose_name='Produto')
    image=models.ImageField(upload_to='product', default='random.jpg')
    description = models.TextField(verbose_name="Descrição", default=" Sem Descrição ")
    price = models.FloatField(help_text='euros cada', verbose_name="Preço")
    category = models.CharField(max_length=20, choices=CATEGORY, blank=True, verbose_name="Categoria")
    
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return f'{self.name} - ({self.category})'


class ProductionState(models.TextChoices):
    PENDENT = 'P', 'Pendente'
    IN_PROD = 'EA', 'Em Produção'
    CONCLUDED = 'C', 'Concluída'

class ProductionOrder(models.Model):
    """
    Ordem de produção
    Pretendo implementar a creação de uma Ordem de Produção
    a quando da chegada de uma encomenda
    verifica se há em stoque se não houver
    cria esta ordem
    """
    prod_order_id = models.CharField(max_length=12, blank=True)
    product = models.OneToOneField(Product, on_delete=models.CASCADE, unique=True, blank=True, verbose_name='Produto')
    quantity_ordered = models.IntegerField(verbose_name= 'Quantidade da Ordem')
    quantity_produced = models.IntegerField(verbose_name='Quantidade Produzida', default = 0)
    state = models.CharField(
        max_length=2,
        choices=ProductionState.choices,
        blank= True,
        null= True,
    )
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if self.quantity_produced == 0:
            self.state = ProductionState.PENDENT
        elif self.quantity_produced == self.quantity_ordered:
            self.state = ProductionState.CONCLUDED
        else:
            self.state = ProductionState.IN_PROD
        
        if self.prod_order_id == '':
            self.prod_order_id =  str(uuid.uuid4()).replace('-', '').upper()[:12]
        
        
        return super().save(*args, **kwargs)

    def call(self):
        return f'{self.product} - Quantidade: {self.quantity_ordered} - Estado: {self.get_state_display()}'

    def __str__(self):
        return f'{self.prod_order_id}'


class Production(models.Model):
    """
    Instâncias de produção:
    Necessario criar sinal que atualiza a ordem de produção
    e atualiza stoque e ecomenda
    """

    production_order = models.ForeignKey(ProductionOrder, on_delete=models.CASCADE, blank=True, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, blank=True, null=True)
    #machine
    quantity = models.IntegerField(verbose_name='Quantidade Produzida')
    time = models.IntegerField(verbose_name= 'Tempo de Produção')
    date = models.DateTimeField(verbose_name='Data de Produção')

    def __str__(self):
        return f'{self.employee.first_name} - {self.quantity} x '

    def save(self, *args, **kwargs):
        if self.date is None:
            self.date = timezone.now()
        return super().save(*args, **kwargs)

class Inventary(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    total_quantity = models.IntegerField(blank=True, null=True, verbose_name = 'Quantidade Total')
    productions = models.ManyToManyField(Production)

    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.product.name} - {self.total_quantity} unidades'

product/forms.py
from django import forms
from django.forms import BaseModelFormSet
from .models import Product, Production, ProductionOrder

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class DateInput(forms.DateInput):
    input_type = 'date'

class ProductionForm(forms.ModelForm):
    class Meta:
        model = Production
        fields = '__all__'
        widgets = {
            'date': DateInput(),
        }

class BaseProductionFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseProductionFormSet, self).__init__(*args, **kwargs)
        self.queryset = Production.objects.none()

class ProductionOrderForm(forms.ModelForm):
    class Meta:
        model = ProductionOrder
        fields = ['product', 'quantity_ordered']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        #Excluir os produtos que já tem ordens de produção
        existing_products = ProductionOrder.objects.values_list('product', flat=True)
        self.fields['product'].queryset = Product.objects.exclude(id__in=existing_products)

product/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.forms import modelformset_factory

from .models import Product, Inventary, ProductionOrder, Production
from .forms import ProductForm, ProductionForm, BaseProductionFormSet, ProductionOrderForm



# PRODUTOS 
def productList(request):
     # Tabela com todos os dados de produtos
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    
    products = Product.objects.filter(
        Q(name__icontains=q) |
        Q(category__icontains=q)
    )
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Produto criado com sucesso!', 'alert-success alert-dismissible')
            return redirect('product:list')
        else:
            messages.warning(request, 'Tentativa falhada!', 'alert-info alert-dismissible')
    context = {
        'objects':products,
        'form':form,
    }
    return render(request, 'product/list.html', context)

def productCreate(request):
        # Formulário de criação de produto.
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Produto criado com sucesso!', 'alert-success alert-dismissible')
            return redirect('product:list')
        else:
            messages.warning(request, 'Tentativa falhada!', 'alert-info alert-dismissible')
    context = {
        'form':form,
    }
    return render(request, 'product/create.html', context)

def productUpdate(request, pk):
    product = get_object_or_404(Product, id=pk)
    form = ProductForm(instance=product)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Produto editado com sucesso!', 'alert-success alert-dismissible')
            return redirect('product:list')
        else:
            messages.warning(request, 'Tentativa falhada!', 'alert-info alert-dismissible')
    
    context = {
        'form':form,
        'obj':product,
    }
    return render(request, 'product/update.html', context)

def productDelete(request, pk):
    product = get_object_or_404(Product, id=pk)
    if request.method == 'POST':
        product.delete()
        messages.success(request, 'Product Deleted!', "alert-success alert-dismissible")
        return redirect('product:list')
    return render(request, 'delete.html', {'obj': product})

def productView(request, pk):
    """
    Vista de um unico produto
    quero adicionar estatisticas de cada produto
    """
    product = get_object_or_404(Product, id=pk)
    try:
        production_order = ProductionOrder.objects.get(product=product)
    except ProductionOrder.DoesNotExist:
        production_order = ProductionOrder.objects.none()
    productions = Production.objects.filter(production_order__product=product)

    total_products = 0
    total_production_time = 0
    production_hour = 0
    profit_per_hour = 0
    total_price = 0
    avarage_production = 0

    if productions != None:

        for production in productions:
            # total de produtos produzidos
            total_products += production.quantity
            # total de horas de produção
            total_production_time += production.time
            # preço total
            total_price = total_products * product.price
            # Quantidade Produzida por Hora
            production_hour = total_products / total_production_time
            # lucro por hora
            profit_per_hour = total_price / total_production_time
            # média de produção
            avarage_production = total_products / productions.count()
            
        production_hour = round(production_hour)
        profit_per_hour = round(profit_per_hour)

        
    context = {
        'obj':product,
        'order':production_order,
        'productions':productions,
        'total_products':total_products,
        'total_production_time':total_production_time,
        'total_price':total_price,
        'production_hour':production_hour,
        'profit_per_hour':profit_per_hour,
        'avarage_production':avarage_production,
    }
    return render(request, 'product/view.html', context)




# INVENTARIO
def inventaryView(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    inv = Inventary.objects.filter(
        Q(product__name__icontains=q)
    )

    context = {
        'objects' : inv,
    }
    return render(request, 'product/inventary.html', context)




#PRODUÇÃO
def productionView(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    productions = Production.objects.filter(
        Q(employee__first_name__icontains=q) |
        Q(inventary__product__name__icontains=q)
    ).order_by('-date')

    ProductionFormSet = modelformset_factory(Production, ProductionForm, extra=1, formset=BaseProductionFormSet)
    formset = ProductionFormSet(queryset=Production.objects.none())
    if request.method == 'POST':
        formset = ProductionFormSet(request.POST)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Produção Adicionada com sucesso!', "alert-success alert-dismissible")
            return redirect('product:prod')

    context = {
        'objects': productions,
        'form':formset,
    }
    return render(request, 'product/production.html', context)

def addProduction(request):

    ProductionFormSet = modelformset_factory(Production, ProductionForm, extra=1, formset=BaseProductionFormSet)
    formset = ProductionFormSet(queryset=Production.objects.none())
    if request.method == 'POST':
        formset = ProductionFormSet(request.POST)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Produção Adicionada com sucesso!', "alert-success alert-dismissible")
            return redirect('product:prod')
    
    context = {
        'form':formset,
    }
    return render(request, 'product/add_prod.html', context)



def productionEdit(request, pk):
    production = Production.objects.get(id=pk)
    form = ProductionForm(instance=production)
    if request.method == 'POST':
        form = ProductionForm(request.POST, instance=production)
        if form.is_valid():
            form.save()
            messages.success(request, 'Produção Atualizada!', 'alert-success alert-dismissible')
            return redirect('product:prod')
        else:
            messages.error(request, 'Falha na Atualização!', 'alert-warning alert-dismissible')
    context = {
        'form':form,
        'production':production,
    }
    return render(request, 'product/edit.html', context )


def productionDelete(request, pk):
    production = get_object_or_404(Production, id=pk)
    if request.method == 'POST':
        production.delete()
        messages.success(request, 'Produção Deleted!', "alert-success alert-dismissible")
        return redirect('product:prod')
    return render(request, 'delete.html', {'obj': production})


#Orem Produção
def productionOrderView(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    
    ordemProd = ProductionOrder.objects.filter(
        Q(product__name__icontains=q)
    )
    products = Product.objects.all()
    form = ProductionOrderForm()
    if request.method == 'POST':
        form = ProductionOrderForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ordem Adicionada com sucesso!', 'alert-success alert-dismissible')
        else:
            messages.error(request, 'ERRO! FORMULARIO NÃO FOI SUBMETIDO !!!', 'alert-warning alert-dismissible')
    context = {
        'objects': ordemProd,
        'form':form,
        'products':products,
    }
    return render(request, 'product/production_order.html', context)


def createProductionOrder(request):
    form = ProductionOrderForm()
    if request.method == 'POST':
        form = ProductionOrderForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ordem Adicionada com sucesso!', 'alert-success alert-dismissible')
            return redirect('product:production-order')
    context = {'form':form}
    return render(request, 'product/add_prod_order.html', context)

product/templates/product/add_prod.html
{% extends 'main.html' %}
{% block content %}
<!-- Adicionar Produção Page -->
<div class="form__product">
    <div class="content px-3 py-3">
        {% include 'form.html' %}
    </div>
</div>
{% endblock content %}

product/templates/product/add_prod_order.html
{% extends 'main.html' %}
{% block content %}
<!-- Adicionar Ordem de Produção Page -->
<div class="form__product">
    <div class="container">
        {% include 'form.html' %}
    </div>
</div>
{% endblock content %}

product/templates/product/card_chart_bar_inv.html
<div class="card mb-2 text-center shadow">
    <div class="card-header bg-secondary"><i class="fa-solid fa-chart-simple"></i></div>
    <div class="card-body mb-2">
        <div class="row p-2">
            <div class="chart-container" style="position: relative; height:25rem; width:48rem">
                <canvas id="myChart1"></canvas>
                <script>
                    var ctx = document.getElementById('myChart1').getContext('2d');
                    var myChart1 = new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: [{% for obj in objects %} '{{obj.product.name}}', {% endfor %}],
                    datasets: [{
                        label: 'Products',
                        data: [{% for obj in objects %} '{{obj.total_quantity}}', {% endfor %}],
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.6)',
                            'rgba(255, 159, 64, 0.6)',
                            'rgba(255, 205, 86, 0.6)',
                            'rgba(75, 192, 192, 0.6)',
                            'rgba(54, 162, 235, 0.6)',
                            'rgba(153, 102, 255, 0.6)',
                            'rgba(201, 203, 207, 0.6)'
                        ],
                            borderColor: [
                                'rgb(255, 99, 132, 0.6)',
                                'rgb(255, 159, 64, 0.6)',
                                'rgb(255, 205, 86, 0.6)',
                                'rgb(75, 192, 192, 0.6)',
                                'rgb(54, 162, 235, 0.6)',
                                'rgb(153, 102, 255, 0.6)',
                                'rgb(201, 203, 207, 0.6)'
                            ],
                                borderWidth: 1
                                                                                                                    }]
                                                                                                                },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                                                                                                            });
                </script>
            </div>
        </div>
    </div>
</div>

product/templates/product/card_chart_pie_inv.html
<div class="card">
    <div class="card-header">Bar Chart</div>
    <div class="card-body">
        <h5 class="card-title"></h5>
        <div class="chart-container " style="position: relative; height:18rem; width:22rem">
            <canvas id="myChart"></canvas>
            <script>
                var ctx = document.getElementById('myChart').getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'pie',
                    data: {
                        labels: [{% for obj in objects %} '{{obj.product.name}}', {% endfor %}],
                datasets: [{
                    label: 'Products',
                    data: [{% for obj in objects %} '{{obj.total_quantity}}', {% endfor %}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.6)',
                        'rgba(255, 159, 64, 0.6)',
                        'rgba(255, 205, 86, 0.6)',
                        'rgba(75, 192, 192, 0.6)',
                        'rgba(54, 162, 235, 0.6)',
                        'rgba(153, 102, 255, 0.6)',
                        'rgba(201, 203, 207, 0.6)'
                    ],
                        borderColor: [
                            'rgb(255, 99, 132, 0.6)',
                            'rgb(255, 159, 64, 0.6)',
                            'rgb(255, 205, 86, 0.6)',
                            'rgb(75, 192, 192, 0.6)',
                            'rgb(54, 162, 235, 0.6)',
                            'rgb(153, 102, 255, 0.6)',
                            'rgb(201, 203, 207, 0.6)'
                        ],
                            borderWidth: 1
                                                                                                                            }]
                                                                                                                        },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
                                                                                                                    });
            </script>
        </div>
    </div>
</div>

product/templates/product/card_chart_pie_p_ord.html
<!-- Chart de Ordens de produção-->
<div class="card flex-fill border-2 illustration p-2 my-2 align-self-center">
    <p class="card-text text-center">
    <h4><strong>{{obj.product.name}}</strong></h4>
    Ordem de : {{obj.quantity_ordered}}
    Produzidas : {{obj.quantity_produced}}
    </p>
    <div class="card-body p-0 d-flex flex-fill">
        <div class="chart-container">
            <canvas id="myChart{{obj.id}}"></canvas>
            <script>
                var ctx = document.getElementById('myChart{{obj.id}}').getContext('2d');
                var myChart{{ obj.id }} = new Chart(ctx, {
                    type: 'pie',
                    data: {
                        labels: ['Quantidade Necessária', 'Quantidade Produzida'],
                        datasets: [{
                            label: 'Ordem de Produção',
                            data: ['{{obj.quantity_ordered}}', '{{obj.quantity_produced}}'],
                            backgroundColor: [
                                'rgba(255, 205, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(54, 162, 235, 0.6)',
                                'rgba(153, 102, 255, 0.6)',
                                'rgba(201, 203, 207, 0.6)'
                            ],
                            borderColor: [
                                'rgb(255, 205, 86, 1)',
                                'rgb(75, 192, 192, 1)',
                                'rgb(54, 162, 235, 0.6)',
                                'rgb(153, 102, 255, 0.6)',
                                'rgb(201, 203, 207, 0.6)'
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        },
                        responsive: true,
                        maintainAspectRatio: false // Desabilita a manutenção da proporção para permitir a adaptabilidade
                    }
                });
            </script>
        </div>
    </div>
</div>

product/templates/product/card_table_inv.html
<div class="card border-2">
    <div class="card-body text-center">
        <table class="table">
            <thead>
                <tr class="table-secondary">
                    <th scope="col">#</th>
                    <th scope="col">Produto</th>
                    <th scope="col">Quantidade Total</th>
                    <th scope="col">Produções</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in objects %}
                <tr>
                    <th scope="row">{{obj.id}}</th>
                    <th>{{obj.product.name}}</th>
                    <th>{{obj.total_quantity}}</th>
                    <th><a class='btn btn-warning btn-sm' href="{% url 'product:view' obj.product.id %}"><i
                                class="fa-regular fa-eye"></i></a></th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

product/templates/product/card_table_order.html
<div class="card border-2">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr class="table-secondary">
                    <th scope="col">#</th>
                    <th scope="col">Produto</th>
                    <th scope="col">Quantidade da Ordem</th>
                    <th scope="col">Quantidade Produzida</th>
                    <th scope="col">Estado</th>
                    <th scope="col">Criada</th>
                    <th scope="col">Atividade</th>

                </tr>
            </thead>
            <tbody>
                {% for obj in objects %}
                <tr>
                    <th scope="row">{{obj.id}}</th>
                    <th>{{obj.product.name}}</th>
                    <th>{{obj.quantity_ordered}}</th>
                    <th>{{obj.quantity_produced}}</th>
                    <th>{{obj.state}}</th>
                    <th>{{obj.created}}</th>
                    <th><a class='btn btn-warning btn-sm' href="{% url 'product:view' obj.product.id %}"><i
                                class="fa-regular fa-eye"></i></a></th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

product/templates/product/list.html
{% extends 'main.html' %}
{% block content %}
<!-- Modal -->
<div class="modal fade" id="employeeModal" tabindex="-1" aria-labelledby="employeeModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="employeeModal">Adicionar Funcionário</h5>
                <button type="button" class="btn btn-warning" data-bs-dismiss="modal" aria-label="Close"><i
                        class="fa-solid fa-xmark"></i></button>
            </div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body">

                    {{ form.name.errors }}
                    <!-- Produto -->
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Produto</span>
                        <input type="text" class="form-control" placeholder="Nome do Produto" aria-label="Produto"
                            name="name" aria-describedby="basic-addon1">
                    </div>
                    {{ form.image.errors }}
                    <!-- Escolher Imagem  -->
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="inputGroupFile01">Fotografia</label>
                        <input type="file" class="form-control" id="inputGroupFile01" name="image">
                    </div>
                    <!-- Descrição -->
                    {{form.description.errors}}
                    <div class="input-group">
                        <span class="input-group-text">Descrição</span>
                        <textarea class="form-control" aria-label="Descrição" name="description"></textarea>
                    </div>
                    <!-- Preço -->
                    {{form.price.errors}}
                    <div class="input-group mb-3">
                        <span class="input-group-text">Preço</span>
                        <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)"
                            name="price">
                        <span class="input-group-text">€</span>
                    </div>
                    <!-- Categoria -->
                    {{ form.category.errors }}
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="inputGroupSelect01">Departamento</label>
                        <select class="form-select" id="inputGroupSelect01" name="category">
                            <option selected disabled>Choose...</option>
                            {% for choice in form.category.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                            {% endfor %}
                        </select>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-warning border-2 text-bottom p-2">Confirmar<span
                            class="badge bg-dark mx-2"><i class="fa-solid fa-check"></i></span></button>
                </div>
            </form>
        </div>
    </div>
</div>



<main class="content px-3 py-2">
    <div class="container-fluid">
        <!-- Ação da Página -->
        <div class="action mb-4 text-end">
            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#employeeModal">
                <i class="fa-solid fa-plus"></i>
            </button>
        </div>

        <div class="card border-0">
            <div class="card-header">
                <h4 class="card-title text-center mt-2">
                    Tabela de Produtos
                </h4>
            </div>
            <!-- Start Table Produtos -->
            <div class="card-body text-center">
                <table class="table bg-white">
                    <thead class="thead-dark">
                        <tr class="table-dark">
                            <th scope="col">#</th>
                            <th scope="col">Produto</th>
                            <th scope="col"> Preço </th>
                            <th scope="col"> Categoria</th>
                            <th scope="col">Atividade</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in objects %}
                        <tr>
                            <th scope="row">{{obj.id}}</th>
                            <td>{{obj.name}}</td>
                            <td>{{obj.price}}</td>
                            <td>{{obj.category}}</td>
                            <td class="text-center">
                                <a class='btn btn-warning btn-sm' href="{% url 'product:view' obj.id %}"><i
                                        class="fa-regular fa-eye"></i></a>
                                <!-- Button triger modal -->
                                <a id="edit-btn" type='button' class='btn btn-success btn-sm edit-btn'
                                    href="{% url 'product:update' obj.id %}"><i
                                        class="fa-solid fa-pen-to-square"></i></a>
                                <a class='btn btn-danger btn-sm' href="{% url 'product:delete' obj.id %}"><i
                                        class="fa-regular fa-circle-xmark"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- End Table Produtos -->
        </div>
    </div>
</main>
{% endblock content %}