dashboard/urls.py
from django.urls import path

from .views import(
    home
)
app_name = 'dashboard'

urlpatterns = [
    path('', home, name='home')
]

human/urls.py
from django.urls import path

from .views import(
    employeesList,
    employeeCreate,
    employeeUpdate,
    employeeDelete,
    employeeView,

    loginPage,
    logoutUser
)

app_name='human'

urlpatterns = [
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),


    path('', employeesList, name='list'),
    path('create/', employeeCreate, name='create'),
    path('update/<str:pk>/', employeeUpdate, name='update'),
    path('delete/<str:pk>/', employeeDelete, name='delete'),
    path('<str:pk>/', employeeView, name='view'),



]

orders/urls.py
from django.urls import path
from .views import(
    search,
    OrderDetailView,
    orderView,
    createOrder,
)
app_name = 'orders'

urlpatterns = [
    path('', search, name='search'),
    path('list/', orderView, name='list'),
    path('detail/<str:pk>/', OrderDetailView.as_view(), name='detail'),
    path('create/', createOrder, name='create'),

]

product/urls.py
from django.urls import path

from .views import (
    productList,
    productCreate,
    productUpdate,
    productDelete,
    productView,

    inventaryView,

    productionView,
    addProduction,
    productionEdit,
    productionDelete,

    productionOrderView,
    createProductionOrder,
)

app_name = 'product'


urlpatterns = [
    #Product
    path('', productList, name='list'),
    path('create/', productCreate, name='create'),
    path('update/<str:pk>/', productUpdate, name='update'),
    path('delete/<str:pk>/', productDelete, name='delete'),
    path('product/<str:pk>/', productView, name='view'),

    #Inventary
    path('inventary/', inventaryView, name="inv"),

    #Productions
    path('production/', productionView, name='prod'),
    path('add-prod/', addProduction, name='add-prod'),
    path('prod-edit/<str:pk>/', productionEdit, name='prod-edit'),
    path('prod-del/<str:pk>/', productionDelete, name='prod-del'),

    #Ordem Produção
    path('productionOrderView/', productionOrderView, name='production-order'),
    path('createProductionOrder/', createProductionOrder, name='add-prod-order'),
]

reports/urls.py
from django.urls import path

from .views import (
    ReportListView,
    ReportDetailView,
    UploadTemplateView,
    csv_upload,
    createReport,
    updateReport,
    renderPDF,
)

app_name = 'reports'

urlpatterns = [
    path('list/', ReportListView.as_view(), name='list'),
    path('upload/', csv_upload, name='upload'),
    path('from-file/', UploadTemplateView.as_view(), name='from-file'),
    path('create-report/', createReport, name='create-report'),
    path('update-report/<str:pk>/', updateReport, name='update-report'),

    path('detail/<str:pk>/', ReportDetailView.as_view(), name='detail'),
    path('detail/<str:pk>/pdf/', renderPDF, name='pdf'),

]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('product/', include('product.urls')),
    path('human/', include('human.urls')),

    path('orders/', include('orders.urls')),
    path('reports/', include('reports.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

templates/alerts.html
<div class="row p-2 text-center">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            <!--span aria-hidden="true">&times;</span-->
        </button>
        {{ message | safe }}
    </div>
    {% endfor %}
</div>

templates/delete.html
{% extends 'main.html' %}

{% block content %}
<div class="form__product">
    <div class="content px-3 py-2">
        <div class="card flex-fill border-0 illustration">
            <div class="card-action text-end">
                <a href="{{request.META.HTTP_REFERER}}" class="btn btn-warning"><i class="fa-solid fa-xmark"></i></a>
            </div>
            <hr>
            <div class="card-body p-0 d-flex flex-fill">
                <div class="p-3 m-1">
                    Tem a certeza que deseja eliminar <strong>{{obj.name}}</strong> ??
                    <hr>
                    <form action="" method="POST">
                        {% csrf_token %}

                        <div class="form__action text-center">
                            <button type="submit" class="btn btn-warning border-2 text-bottom p-2">Confirmar<span
                                    class="badge bg-dark mx-2"><i class="fa-solid fa-check"></i></span></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/footer.html
<!-- Start Footer -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row text-muted">
            <div class="col-6 text-start">
                <p class="mb-0">
                    <a href="#" class="text-muted">
                        <strong>devMotcho</strong>
                    </a>
                </p>
            </div>
            <div class="col-6 text-end">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a href="#" class="text-muted">Contact</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" class="text-muted">About Us</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" class="text-muted">Terms</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" class="text-muted">Booking</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- End Footer -->

templates/form.html
{% load crispy_forms_tags %}

<div class="card flex-fill border-0 illustration">
    <div class="card-action text-end">
        <a href="{{request.META.HTTP_REFERER}}" class="btn btn-warning"><i class="fa-solid fa-xmark"></i></a>
    </div>
    <hr>
    <div class="card-body p-0 d-flex flex-fill">
        <div class="p-3 m-1">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <div class="form__action text-center">
                    <button type="submit" class="btn btn-warning border-2 text-bottom p-2">Confirmar<span
                            class="badge bg-dark mx-2"><i class="fa-solid fa-check"></i></span></button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/main.html
<!doctype html>
{% load static %}
<html lang="en" data-bs-theme="dark">

<head>
    <!-- Meta data -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Title tags -->
    <title>{% block title %} {% endblock title %}</title>

    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    {% block scripts %} {% endblock scripts %}

    <!-- Bootstrap 5 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/af0ff4f1fc.js" crossorigin="anonymous"></script>

    <!-- Chart Js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>
    <div class="wrapper">
        {% include 'sidebar.html' %}
        <div class="main">
            {% include 'navbar.html' %}
            {% include 'alerts.html' %}
            {% block content %}
            {% endblock content %}
            <a href="#" class="theme-toggle">
                <i class="fa-regular fa-moon"></i>
                <i class="fa-regular fa-sun"></i>
            </a>
            {% include 'footer.html' %}
        </div>
    </div>


    <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/navbar.html
{% load static %}
{% if request.user.is_authenticated %}
<nav class="navbar navbar-expand px-3 border-bottom">
    <button class="btn" id="sidebar-toggle" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Search -->
    <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-warning" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
    <!-- Avatar dropdown -->
    <div class="navbar-collapse navbar">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a href="#" data-bs-toggle="dropdown" class="nav-icon pe-md-5 mx-4">
                    <i class=" fa-solid fa-gear"></i>
                    <!-- <img src="{{user.profile.avatar.url}}" class="avatar img-fluid rounded" alt=""> -->
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                    <a href="#" class="dropdown-item"><i class="fa-solid fa-user"></i> Profile</a>
                    <a href="#" class="dropdown-item"><i class="fa-solid fa-gears"></i> Settings </a>
                    <a href="{% url 'human:logout' %}" class="dropdown-item"><i class="fa-solid fa-door-open"></i>
                        Logout</a>
                </div>
            </li>
        </ul>
    </div>
    <!-- End Avatar Dropdown -->
</nav>
{% endif %}

templates/sidebar.html
{% if request.user.is_authenticated %}

<aside id="sidebar" class="js-sidebar">
    <!-- Content for sidebar -->
    <div class="h-100">
        <div class="sidebar-logo bg-secondary text-center text-warning">
            <a href="{% url 'dashboard:home' %}">DataMotive</a>
        </div>
        <ul class="sidebar-nav">
            <li class="sidebar-header">
            </li>
            <hr>
            <!-- Home -->
            <li class="sidebar-item">
                <a href="{% url 'dashboard:home' %}" class="sidebar-link">
                    <i class="fa-solid fa-house"></i>
                    Home
                </a>
            </li>
            <hr>
            <!-- Relatórios -->
            <li class="sidebar-item">
                <a href="{% url 'reports:list' %}" class="sidebar-link">
                    <i class="fa-solid fa-file-lines pe-2"></i>
                    Relatórios
                </a>
            </li>
            <!-- Fim Relatórios -->
            <hr>
            <!-- Start Produção, Ordens de Produção  -->
            <li class="sidebar-item">
                <a href="#" class="sidebar-link collapsed" data-bs-target="#posts" data-bs-toggle="collapse"
                    aria-expanded="false">
                    <i class="fa-solid fa-sitemap"> </i>
                    Produção
                </a>
                <ul id="posts" class=" sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                    <li class="sidebar-item">
                        <a href="{% url 'product:list' %}" class="sidebar-link">Produtos</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="{% url 'product:prod' %}" class="sidebar-link">Tabela de Produções</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="{% url 'product:add-prod' %}" class="sidebar-link">Adicionar Produções</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="{% url 'product:production-order' %}" class="sidebar-link">Ordens de Produção</a>
                    </li>
                </ul>
            </li>
            <!-- End Produção, Ordens de Produção  -->
            <hr>
            <!-- Start Human Resorces -->
            <li class="sidebar-item">
                <a href="#" class="sidebar-link collapsed" data-bs-target="#auth" data-bs-toggle="collapse"
                    aria-expanded="false">
                    <i class="fa-solid fa-regular fa-user pe-2"></i>
                    Recursos Humanos
                </a>
                <ul id="auth" class=" sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                    <li class="sidebar-item">
                        <a href="{% url 'human:list' %}" class="sidebar-link">Funcionários</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link">Clientes</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link">Colaboradores</a>
                    </li>
                </ul>
            </li>
            <!-- End Human Resorces -->
            <hr>
            <!-- Start Logistica  -->
            <li class="sidebar-item">
                <a href="#" class="sidebar-link collapsed" data-bs-target="#log" data-bs-toggle="collapse"
                    aria-expanded="false">
                    <i class="fa-solid fa-boxes-stacked"></i>
                    Logistica
                </a>
                <ul id="log" class=" sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                    <li class="sidebar-item">
                        <a href="{% url 'orders:search' %}" class="sidebar-link">Encomendas</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="{% url 'product:inv' %}" class="sidebar-link">Inventário</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="{% url 'orders:create' %}" class="sidebar-link">Criar Encomenda</a>
                    </li>
                    <li class="sidebar-item">
                        <a href="{% url 'orders:list' %}" class="sidebar-link">Lista Encomendas</a>
                    </li>
                </ul>
            </li>
            <!-- End Logistica  -->
            <hr>
            <!-- Start CSV file add -->
            <li class="sidebar-item">
                <a href="{% url 'reports:from-file' %}" class="sidebar-link">
                    <i class="fa-solid fa-file-import"></i>
                    CSV
                </a>
            </li>
            <hr>
            <!-- End CSV file add -->
        </ul>
    </div>
</aside>
{% endif %}